export default {
    LOGIN_STARTED: 'login_started',
    LOGIN_SUCCESS: 'login_success',
    LOGIN_FAILED: 'login_failed',
    SIGNUP_STARTED: 'signup_started',
    SIGNUP_SUCCESS: 'signup_success',
    SIGNUP_FAILED: 'signup_failed',
    LOGOUT: 'logout',
    LOGOUT_SUCCESS: 'logout_success',
    LOGOUT_FAILED: 'logout_failed',
    GET_HISTORY: 'get_history',
    GET_HISTORY_SUCCESS: 'get_history_success',
    GET_HISTORY_FAILED: 'get_history_failed',
    DELETE_DETECTED_SIGNAL: 'delete_detected_signal',
    ADD_PREDICTIONS_TO_HISTORY: 'add_predictions_to_history',
    GET_CAMERA_ROLL_PERMISSION: 'get_camera_roll_permission',
    GET_CAMERA_ROLL_PERMISSION_SUCCESS: 'get_camera_roll_permission_success',
    GET_CAMERA_ROLL_PERMISSION_FAILED: 'get_camera_roll_permission_failed',
    GET_CAMERA_PERMISSION: 'get_camera_permission',
    GET_CAMERA_PERMISSION_SUCCESS: 'get_camera_permission_success',
    GET_CAMERA_PERMISSION_FAILED: 'get_camera_permission_failed',
    GET_PREDICTIONS: 'get_predictions',
    GET_PREDICTIONS_SUCCESS: 'get_predictions_success',
    GET_PREDICTIONS_FAILED: 'get_predictions_failed',
    CLEAR_PREDICTIONS: 'clear_predictions'
};
